### ISSUE TITLE
[Bug] Workspace sometimes shows as a shell command

### ISSUE THREAD

**Issue by andweeb** [andweeb/presence.nvim#10]
> Do you know why sometimes the git repository I'm working in sometimes shows as a shell command? For example:
![Bug](https://user-images.githubusercontent.com/48545987/118083533-a17df500-b3ae-11eb-899e-4e162c03d857.png)
The file path for this is
```
latex [The github repository]
|- Spring 2021
  |- [Other subfolders]
  |- Physics 1C
    |- [Other files....]
    |- Lec25.tex
```

_Originally posted by @kylechui in https://github.com/andweeb/presence.nvim/issues/9#issuecomment-840320867_

**Comment by andweeb** [comment]
@kylechui Can you inspect the full workspace text and paste that here?

It seems like there's an issue with the bash command used to get the git repository name.

**Comment by kylechui** [comment]
Sorry for commenting on the other issue, wasn't sure what proper "github etiquette" would be. Here's the text from the command (I had to hover over it to get it):
![image](https://user-images.githubusercontent.com/48545987/118151950-b769d500-b403-11eb-978b-ef63f782d1d2.png)
Based on my own testing with other files/repositories, I'm pretty sure it's because my folders have spaces in their names. I recreated the file structure but omitted the spaces from all my file names, and it worked out.

**Comment by andweeb** [comment]
No worries! You're spot on, it looks like I wasn't properly escaping spaces in the command to get the git project name.

I've just pushed a branch `project-name-escape-fix` that should resolve the issue. I don't have much time today to test it out, would you mind pointing your plugin to that branch and seeing if that fixes it?

It'd be something like
* `Plug 'andweeb/presence.nvim', { 'branch': 'project-name-escape-fix' }` for `vim-plug`
* `use { 'andweeb/presence.nvim', branch = 'project-name-escape-fix' }` for `packer.nvim`

**Comment by kylechui** [comment]
Seems to work perfectly, I tried a few other files/repositories and have no issues. Thanks!

**Comment by andweeb** [comment]
Awesome! I just merged it into `main` so you can remove that branch option now :) I'll resolve this!
