### ISSUE TITLE
How would I change the images of if I wanted to?

### ISSUE THREAD

**Issue by KarlWithK** [andweeb/presence.nvim#11]
I really want to change the images if possible, which file would I need to look at? I look through the code, but I'm not very familiar with lua.

**Comment by andweeb** [comment]
The mapping of file names and extensions to their metadata is in [`file_assets.lua`](https://github.com/andweeb/presence.nvim/blob/main/lua/presence/file_assets.lua) and the asset files themselves are tracked in [this Dropbox folder](https://www.dropbox.com/sh/j8913f0gav3toeh/AADxjn0NuTprGFtv3Il1Pqz-a?dl=0), though they're tied to the [Discord application](https://discord.com/developers/applications) specific to this project.

Is it that you want to add an image for a file type not currently supported, or do you want to use your own custom image for an existing file type?

**Comment by KarlWithK** [comment]
I would like to use a custom image for an existing file type. In either case I see, and thanks for explaining.

**Comment by andweeb** [comment]
O I see, I actually had already considered adding an option to allow for doing this! However, there's no explicit support for this right now as I haven't gotten around to it yet (you can see the relevant card [here](https://github.com/andweeb/presence.nvim/projects/1#card-60538725)).

Unfortunately the images are tied to assets that are manually uploaded to a Discord application, so for example if you were to want to override the Lua image, you'd need to create your own Discord application and manually upload your custom image. I'm considering the config to be something like:
```lua
require("presence"):setup({
    file_assets = {
        lua = { "Lua", "<custom_asset_name>", "<description>", "<custom_client_id>" },
    },
})
```

Unless you want to wait for me to implement this feature (or give it a shot yourself!), what you can do instead is create your own Discord application and upload _all_ the assets in that Dropbox folder and your custom image with the same name, and in your config set the `g:presence_client_id` to your Discord application's client id, essentially somewhat "forking" the default Discord application. Kinda overkill considering all you want to do is use a custom image for a single existing file type, but that'll work if you'd like to use your own custom image ASAP.

**Comment by GustavoPrietoP** [comment]
This would be amazing tbh :)

**Comment by itsmeboy0** [comment]
> Unfortunately the images are tied to assets that are manually uploaded to a Discord application, so for example if you were to want to override the Lua image, you'd need to create your own Discord application and manually upload your custom image.

@andweeb Discord has silently added the ability to use an image link for the large image key ([Source](https://twitter.com/realBas950/status/1474072825103331330), large image key only sadly).

**Comment by itsmeboy0** [comment]
> @itsmeboy0 Nice find! 💯
> 
> I'll try it out and brainstorm a sane way to configure this sometime this weekend :)

I have tested putting an image URL in the small image key and it seems to work as well.

**Comment by andweeb** [comment]
@itsmeboy0 Hah this has turned out to be a pretty awesome feature, thanks for letting me know about this!

With Discord's support for image URLs, I can see this actually opening up a lot of other potential opportunities for this plugin:
* having a centralized repository to host and track changes to art assets to enable better community collaboration and discussion
* leveraging the repository to no longer have to deal with manually uploading assets in Discord's clunky art asset UI
* enabling functionality to add fun user-configured states ("out for lunch", "taking a break", etc.)

I haven't done much digging but hopefully this is an official feature that's here to stay!

---

@KarlWithK @GustavoPrietoP You should now be able to use your own custom images for both supported and unsupported file types in presence.nvim by using the `file_assets` setup option (see details in the [README](https://github.com/andweeb/presence.nvim#configuration)). For example, if you wanted to replace the existing gopher icon for `*.go` files with the rebranded Go logo and add support for some custom file named `GustavoPrietoP.txt`, you could configure presence.nvim like this:
```lua
require("presence"):setup({
    file_assets = {
        go = { "Go", "https://go.dev/blog/go-brand/Go-Logo/PNG/Go-Logo_Aqua.png" },
        ["GustavoPrietoP.txt"] = { "GustavoPrietoP", "https://avatars.githubusercontent.com/u/70907734?v=4" },
    },
})
```
<img width="182" alt="Screen Shot 2022-01-15 at 11 28 49 PM" src="https://user-images.githubusercontent.com/10726590/149651329-2abfc1c4-dbdf-4676-95d3-0aa557b5af79.png">
<img width="244" alt="Screen Shot 2022-01-15 at 11 29 01 PM" src="https://user-images.githubusercontent.com/10726590/149651327-ee34da9c-9d60-4796-ba3d-791d9ec37fec.png">
