### ISSUE TITLE
attempt to call method 'set_option' (a nil value)

### ISSUE THREAD

**Issue by CleoMenezes** [andweeb/presence.nvim#54]
After installing and configuring, I can't get presence.nvim to work
![image](https://user-images.githubusercontent.com/54215258/147890911-d8155f27-28bd-47d9-b0ee-d0c1c1ef06f8.png)

**Comment by Wolfdesroyer8** [comment]
I'm having the same issue can you tell me how you fixed it.

**Comment by andweeb** [comment]
Hi @Wolfdesroyer8! The `setup` function passes `self` as the first parameter so you'll need to invoke [using a colon](https://www.lua.org/pil/16.html) instead of a dot:
```lua
require("presence"):setup({
    -- your setup options here
})
```

You can see in @CleoMenezes's `init.lua` in the screenshot above the plugin is set up with `require("presence").setup`, which results in this `attempt to call method` error.
