### ISSUE TITLE
Where do you set the "Neovim" title

### ISSUE THREAD

**Issue by Dankni95** [andweeb/presence.nvim#55]
Hi,

Could you point me to where in the code is the title "Neovim" set?

![image](https://user-images.githubusercontent.com/71786017/148746391-5d887394-e811-4cb0-987c-cea72d37c7ed.png)

I would like to change it, as far as i know this is not an option so i need to do it manually in code?

**Comment by andweeb** [comment]
Hi @Dankni95! That title is the name of the "game" in the context of Discord Rich Presence. As far as I know it's not possible to configure the game name via RPC.

To achieve this you'll most likely have to create your own [Game SDK application](https://discord.com/developers/applications) in Discord, configure the main app icon and name that you want to replace "Neovim" with, and under Rich Presence upload all [presence.nvim assets](https://www.dropbox.com/sh/j8913f0gav3toeh/AADxjn0NuTprGFtv3Il1Pqz-a?dl=0), and then finally configure presence.nvim to use your application id instead of the default `793271441293967371` id:
```lua
require("presence"):setup({ client_id = "<your-application-id-here>" })
```

Cumbersome for sure and not really future-proof as new assets in the default Neovim Discord application won't be reflected automatically, but I don't think Discord provides any API support for customizing that title outside of the application settings in the UI.

 So I'll close this issue for now, but feel free to re-open if you find out a method to achieve this in code!

**Comment by ribeiroevandro** [comment]
@andweeb andweeb thank you very much for the explanation, I created an application here with the intention of changing the title, but the images are not loaded, is there a pattern that I need to follow?

<img width="165" alt="Screenshot 2023-01-19 at 20 03 02" src="https://user-images.githubusercontent.com/943553/213581538-8128ff27-6183-4d75-9b87-a17ee94acafe.png">

**Comment by andweeb** [comment]
Hi @ribeiroevandro, sorry for the late response!

Looks like the main image and file asset images aren't loading in your screenshot. Did you make sure to upload all [presence.nvim assets](https://www.dropbox.com/sh/j8913f0gav3toeh/AADxjn0NuTprGFtv3Il1Pqz-a?dl=0) under your custom Discord application and configure the plugin with the `client_id` option as I outlined in the comment [here](https://github.com/andweeb/presence.nvim/issues/55#issuecomment-1009195205)?

**Comment by ribeiroevandro** [comment]
@andweeb good night!

A silly question, just like on Spotify it appears listening, is it possible to change the "playing" to another term? "Working with" for example?

<img width="213" alt="Screenshot 2023-03-31 at 00 06 42" src="https://user-images.githubusercontent.com/943553/229012748-a69f9bd3-5cee-47db-bf18-b3b3746fb4f9.png">
