### ISSUE TITLE
[Void Linux] Error while processing textchanged autocommands for "*"

### ISSUE THREAD

**Issue by siduck** [andweeb/presence.nvim#6]
I keep getting this error , I use neovim 0.5 
![image](https://user-images.githubusercontent.com/59060246/116504928-2ceb8680-a8d7-11eb-9cd1-7b27450f7df6.png)

**Comment by andweeb** [comment]
Hi @siduck76! It looks like the Discord IPC socket wasn't able to be found on your system. What OS are you using?

**Comment by siduck76** [comment]
I  use void linux , do I need to install this discord IPC socket?

**Comment by andweeb** [comment]
Hmm okay I see, nah it's not something you need to install!

It looks like I need to support the case where named pipes aren't in tmp runtime directories. It's likely that on your system the IPC socket is in this location: `/run/user/{userid}/discord-ipc-0`.

Can you confirm that that's the case? You can find your `userid` with `id -u $USER`.

**Comment by siduck76** [comment]
![image](https://user-images.githubusercontent.com/59060246/116506636-4abaea80-a8db-11eb-8898-67da0c7a7752.png)

**Comment by siduck76** [comment]
@siduck76 My /run/user is empty ,do I need to install this? https://github.com/iamtraction/discoIPC

**Comment by andweeb** [comment]
Nah there shouldn't be anything to install other than your Discord application and ensure that Discord is running, as the client will automatically initialize and open the socket on your system somewhere. We just gotta find where that is lol

I did some light research on Discord on Void Linux, and I'm starting to suspect it may be due to how the application is packaged for your system. Are you using the flatpak version by any chance? It seems there's some limitations and/or extra work into enabling Rich Presence ([see here](https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc))).

Otherwise, try searching for the discord IPC socket location via `netstat -u | grep discord` (assuming `netstat` is available), and let me know if you can find it!

**Comment by siduck76** [comment]
discord is available on void but its a restricted package so I have to use xbps-src to build it , So I just used xdeb to install discord (deb file) , xdeb is a tool that converts xdeb to xbps packages https://github.com/toluschr/xdeb.

**Comment by andweeb** [comment]
Hmm you ran that command while Discord was running right?

If Discord is running and for some reason it doesn't open a socket for the plugin to connect to, I'm not exactly sure if there's a fix I can apply on my end. :/

Coincidentally I've been meaning to try out Void (and Arch) so when I have the time I'll try setting that up and install Discord myself to be able to replicate your issue locally, though it may be a while.

Until then it'd be helpful if you could let me know if you come across more information, such as the `discord-ipc-0` socket location on your system or whether Discord on Void Linux actually does support Rich Presence.

**Comment by siduck76** [comment]
![image](https://user-images.githubusercontent.com/59060246/116640309-3680f700-a988-11eb-8bc8-34b73d2f2ecd.png)
No worries I'll wait! and check about the discord-ipc-0 .

**Comment by OliverKovacs** [comment]
> I keep getting this error , I use neovim 0.5
> ![image](https://user-images.githubusercontent.com/59060246/116504928-2ceb8680-a8d7-11eb-9cd1-7b27450f7df6.png)

I've encountered the same issue using Ubuntu 20 on WSL2.

**Comment by andweeb** [comment]
Thanks for reporting @OliverKovacs! I've not yet added support for WSL on Windows, I'll add that note to the README.

Regarding the error, that occurs when the Discord IPC socket is unable to be found (due to lack of support for Void Linux and WSL at the moment). I'll make a fix to properly handle the error and have a more helpful/informative log here.

**Comment by JuniorSuperTux** [comment]
I wonder if I'm a similar situation. I'm also on Void Linux, and the following appears when the plugin executes:
```
[presence.nvim] Failed to determine Discord IPC socket path    
```

However, when I look into the `/tmp` folder, I do see the file `discord-ipc-0`:
![image](https://user-images.githubusercontent.com/65844719/161389667-f9f28ea8-f476-41c8-98bf-2c3cd2a00f26.png)

What should I do?

**Comment by JuniorSuperTux** [comment]
I think I found the problem:
![image](https://user-images.githubusercontent.com/65844719/161389797-a359aecd-7584-4fa9-96bb-4f0e47e1d71a.png)

All of these are not set in Void Linux by default

**Comment by JuniorSuperTux** [comment]
@siduck Try adding the following to your `.xinitrc`:
```
export TMPDIR=/tmp
```
It worked for me

**Comment by siduck** [comment]
> @siduck Try adding the following to your `.xinitrc`:
> 
> ```
> export TMPDIR=/tmp
> ```
> 
> It worked for me

cool works :D

**Comment by xbz-24** [comment]
> I think I found the problem: ![image](https://user-images.githubusercontent.com/65844719/161389797-a359aecd-7584-4fa9-96bb-4f0e47e1d71a.png)
> 
> All of these are not set in Void Linux by default


which file is this im getting this same error and adding that line to my xinitrc didnt fix it, but im not using void but artix,

![Uploading image.png…]()

**Comment by xbz-24** [comment]
> I think I found the problem: ![image](https://user-images.githubusercontent.com/65844719/161389797-a359aecd-7584-4fa9-96bb-4f0e47e1d71a.png)
> 
> All of these are not set in Void Linux by default


which file is this im getting this same error and adding that line to my xinitrc didnt fix it, but im not using void but artix,

![image](https://github.com/andweeb/presence.nvim/assets/68678258/b466a6c9-3ccf-4d26-957b-eabe92a7dd42)
