### ISSUE TITLE
please make one for helix editor :")

### ISSUE THREAD

**Issue by dr-nemesis-96** [andweeb/presence.nvim#71]
it would be great if helix had a plugin like this, can you please port it,

**Comment by andweeb** [comment]
Haha that might be tough for a couple reasons, like not being familiar with helix and never have written Rust before. But more importantly, it looks like the plugin system in helix [hasn't actually been finalized yet](https://github.com/helix-editor/helix/wiki/FAQ#how-to-write-plugins--is-there-a-plugin-system-in-place-yet-)?

I may be intrigued to give it a shot in the future when they've come out with stable support for plugin development, but I'll close this for now since it's not related to this project.

Feel free to remind me on Discord at [droob#1322](https://discordapp.com/users/241953146232897550) when there is helix plugin support. :)
