### ISSUE TITLE
[Bug] Status not updating after closing file explorer

### ISSUE THREAD

**Issue by kylechui** [andweeb/presence.nvim#9]
OS: Ubuntu 20.04
Latest nightly of Neovim

When I open Nvim-tree.lua, my status updates to say `Editing NvimTree`, as expected. However, when I close the tree, it doesn't automatically revert back to the file that I have open. Rather, I have to edit the file that I have open and delete text before it registers that I'm no longer in the file tree. For example, I would need to delete a few words from `test.lua` before it would say `Editing test.lua`, otherwise it would stay as `Editing NvimTree`.

Side feature request: Can we have a LaTeX logo for `.tex` files as well?

**Comment by andweeb** [comment]
Hi @kylechui, sorry for the late response! I haven't had much time to work on personal projects lately :'/

Yeah this one's actually part of a larger issue, as noted it in [this card](https://github.com/andweeb/presence.nvim/projects/1#card-60538745). Specifically, presence.nvim currently doesn't track state for multiple windows in a single nvim instance, and nvim-tree (along with NERDTree, defx.nvim, etc.) basically falls under that since it opens a new window to display the file explorer.

This has been generally pretty high priority on my mind, so I'll get to it when I can. Thanks for reporting!

P.S. Update your plugins, editing `.tex` files should now update your Discord Presence :^)

**Comment by kylechui** [comment]
The `.tex` files work wonderfully now, thanks a lot! By the way, do you know why sometimes the git repository I'm working in sometimes shows as a shell command? For example:
![Bug](https://user-images.githubusercontent.com/48545987/118083533-a17df500-b3ae-11eb-899e-4e162c03d857.png)
The file path for this is
```
latex [The github repository]
|- Spring 2021
  |- [Other subfolders]
  |- Physics 1C
    |- [Other files....]
    |- Lec25.tex
```
P.S. Thanks again for all your work on this plugin

**Comment by andweeb** [comment]
Whoa that's interesting. I've created #10 since it's a separate issue, mind giving me some more info there?

**Comment by andweeb** [comment]
Hi @kylechui! I just pushed a bug fix for this at `bug/fix-multi-window-presence` (surprisingly a pretty quick fix!). I still have to handle some [edge cases](https://github.com/andweeb/presence.nvim/projects/1#card-60538745) and do more smoke tests, but you can try it out if you'd like.

It should generally work as expected besides those edge cases, but if you do end up trying it out let me know if you come across any other issues! 🙏

**Comment by kylechui** [comment]
I just tested opening/closing NvimTree, help files, and regular files, and it all seems to work very well! As a side thought/suggestion, what do you think about adding `Idling...` to `get_status_text`? Currently, when you launch Neovim or move to an empty buffer, the rich presence disappears, and I'm not sure if having an "Idle" message would be better.

**Comment by andweeb** [comment]
Hi @kylechui! Just FYI I just pushed changes to resolve this issue and address all edge cases I mentioned in the prior comment. As a bonus all Rich Presence updates should now also feel much snappier across multiple windows and across multiple nvim instances :)

I'll be resolving this issue, but of course let me know if you run into any issues with these latest changes. Thanks for reporting this! 👌
